### PR TITLE
update theme to coklat

### PR DESCRIPTION
**Pull request by Alivican**
when it's day 4 but the assets are labeled day 5 because it's the 5th day but it is day 4 but the name the 5 day but because the when the but

### CODE REVIEW

**Comment by ARoyyanF** [comment]
> when it's day 4 but the assets are labeled day 5 because it's the 5th day but it is day 4 but the name the 5 day but because the when the but

😂

**Review by ARoyyanF — APPROVED** [review]
lgtm

**Comment by ARoyyanF** [comment]
eiya background /authpage/login & /authpage/resetpassword blm diganti @Alivican

**Comment by Alivican** [comment]
Oiya wait

**Pull request merged**
